sequenceDiagram
 Participant GH as GitHub
 Participant U as User
 Participant CA as Compromised 3rd Party App
 Participant BA as Bad Actor doing Compromise
 Participant PR as Public Repo
 Participant SR as Sensitive Repo

note over GH,SR: Initial state: uninfected User with commit access to both repositories.

note over U: Use Full Permission App on Public Repo
U -->>CA: OAuth login
CA->>+BA: non-expiring OAuth token
note over BA: Unauthorized API Access Obtained
Note over U: Account Owned until OAuth token deleted
BA->>GH: Insert additional SSH & GPG Public Keys
note over BA: Unauthorized CLI Access Obtained
BA-->>+BA:
Note over U: Account Owned until new keys deleted
opt Normal User <-> Repo usage, mediated by App, is normal
    U -->> CA:
    CA -->>PR:
    PR -->>CA:
    CA -->>U:
end
U -->>CA: Logout (does not revoke token)

U -->>GH: Delete token via UI
BA -->>-BA: Unauthorized OAuth (API) Access Lost

note over U,SR: Attack at any later time
BA ->> SR: Push Signed commits to GitHub
note over SR: Integrity Compromised

U ->>GH: Notice & delete rogue keys
BA-->-BA: Unauthorized GitHub (cli) Access Lost
